name = "Perseus"
author = "minecraftbossdj"
version = "4.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8ca3d4164e295ad6953c12de7212ee110e767948f2095f88a2f9a0fca83b7167"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
