name = "Perseus"
author = "minecraftbossdj"
version = "RELEASE-1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c977ed2d08314a2d45bdd19f782e9b299ca42eb6a34b4d0f700ab66ba14829b1"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
