name = "Perseus"
author = "minecraftbossdj"
version = "4.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e526e1237f8244cb8b65e272ac4b059a089e358c71eea82471bbfc138ed69f04"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
